apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    description: Service-ExternalPriceCollector
  labels:
    app: external-price-collector
    environment: Development
    tier: Service
  name: external-price-collector
  namespace: liquidity
spec:
  revisionHistoryLimit: 1
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: external-price-collector
  template:
    metadata:
      labels:
        app: external-price-collector
      name: external-price-collector
    spec:
      containers:
      - name: external-price-collector
        image: docker.io/swisschains/external-price-collector:latest
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command:
             - /bin/sh
             - -c 
             - "/bin/echo 'options single-request-reopen' >> /etc/resolv.conf"
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /api/isalive
            port: 5000
          initialDelaySeconds: 40
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/isalive
            port: 5000
          initialDelaySeconds: 40
          periodSeconds: 20
        resources:
          requests:
            memory: 64Mi 
            cpu: 40m 
          limits:
            memory: 128Mi 
            cpu: 500m 
        env:
        - name: SeqUrl
          value: "http://seq.common"
        - name: RemoteSettingsUrl
          valueFrom:
            secretKeyRef:
              name: external-price-collector
              key: RemoteSettingsUrl